fix(pyproject): remove unneeded and indirect dependencies
pyproject.toml should only list the dependencies directly used by
CaPyCli, so remove any indirect or outdated dependencies. This also
fixes a conflict with the newer "wheel" version on Debian trixie:

[...]
Installing collected packages: spinners, sortedcontainers, pytz, boolean.py, wheel, urllib3, tzlocal, typing-extensions, types-setuptools, termcolor, soupsieve, six, semver, rpds-py, regex, pyjwt, packageurl-python, license-expression, importlib-resources, et-xmlfile, defusedxml, colorama, cli-support, attrs, validation, requirements-parser, requests, referencing, python-dateutil, py-serializable, openpyxl, log_symbols, beautifulsoup4, sw360, jsonschema-specifications, halo, dateparser, cyclonedx-python-lib, jsonschema, capycli
  Attempting uninstall: wheel
    Found existing installation: wheel 0.46.1
error: uninstall-no-record-file

× Cannot uninstall wheel 0.46.1
╰─> The package's contents are unknown: no RECORD file was found for wheel.

hint: The package was installed by debian. You should check if it can uninstall the package.